46 adding opacity and changing button css
petabencana/cognicity-cards-ng pull request #49
Opened 2023-08-30 06:50 UTC by Ssravani272

Report-type-buttons size has been aligned to the previous and next buttons, and the opacity of the logo and title in the header will change after the report-type -buttons are triggered. All the hazards will have the report-type-buttons before going through the reporting of the hazards.

2023-08-31 06:50 UTC, ruthvik129 requested changes

2023-08-31 06:50 UTC, ruthvik129 commented on src/environments/id/environment.json
@Ssravani272 Revert this file changes in your issue branch and push
Line 9 : data_server": "https://dev-api.petabencana.id/" 
Make sure your issue branch also is having the same if not change it to the above mentioned url

2023-08-31 08:25 UTC, Ssravani272 commented on src/environments/id/environment.json
Reverted the file

2023-09-04 07:03 UTC, ruthvik129 approved these changes

2023-09-04 07:04 UTC, merged